### ISSUE TITLE
Is there any plan to add freetype to cv2?

### ISSUE THREAD

**Issue by violet17** [opencv/opencv-python#305]
It is very hard to put UTF-8 such as Chinese on videos.
The PIL way needs to transform the image, which is not o good way.

### Expected behaviour

Write here how did you expect the library to function.

### Actual behaviour

Write here what went wrong.

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

**Comment by asmorkalov** [comment]
TrueType fonts support has been added to OpenCV next branch:
- PR: https://github.com/opencv/opencv/pull/18403
- Related ticket https://github.com/opencv/opencv/pull/18403

The functionality will be available with OpenCV release 5.0.

**Comment by violet17** [comment]
@asmorkalov  Thanks for your reply.
