### ISSUE TITLE
macOS crash in imshow with Qt5.15

### ISSUE THREAD

**Issue by skvark** [opencv/opencv-python#376]
See https://github.com/opencv/opencv/issues/18079 for background.

I do not own a Mac so I cannot fix this easily by myself without trial and error which will take a lot of time. As a summary, `Info.plist` file should exist in the packages.

Similar issue in PyQt (note that their package structure is different): https://riverbankcomputing.com/pipermail/pyqt/2020-January/042419.html 

Related things in this repository:

- Some Qt related stuff is already copied during the build process to the packages: https://github.com/skvark/opencv-python/blob/master/patches/patchQtPlugins
- Some Qt related environment variables are set during import https://github.com/skvark/opencv-python/blob/master/cv2/__init__.py

**Comment by skvark** [comment]
As a hotfix I'll publish new packages with Qt downgraded to 5.13. This issue needs to however solved somehow in the future.

**Comment by stuf** [comment]
What timing! Stumbled upon this problem just 30 minutes ago, I'll have a look if it works.

**Comment by skvark** [comment]
Note that there is no new release yet, it will take a couple of days to go back to Qt 5.13. But it would be good if someone could have a look into copying the `Info.plist` file to packages.

**Comment by skvark** [comment]
Here is also some of the existing plugin copying code: https://github.com/skvark/opencv-python/blob/d356af12a31fbcb6b7a82372555a7569639bb483/setup.py#L189

**Comment by skvark** [comment]
Qt is now forced to version 5.13.2 on macOS which should work as a temporary fix. New versions should be available in PyPI during next few days.

**Comment by jdifran** [comment]
@skvark I notice after upgrading to opencv-python 4.4.0.40 or 4.4.0.42 (using pip install opencv-python) on macOS 10.12 there are issues with cv2.imshow().  Zoom and pixel/location functionality is broken.  

I've tracked this down to QT not being included in the new pypi package for macOS, but I don't know why this is, especially based on this thread which mentions it being updated.  I've tried building the wheel locally as well and QT is no longer available under the listed GUI in cv2.getBuildInformation():

  GUI: 
    Cocoa:                       YES
    VTK support:                 NO

I was previously on opencv-python 4.1.1.26 where QT is listed under GUI, and cv2.imshow is working fine.  I was upgrading for SIFT support as well as other new opencv features but this is a blocker as I have tools built with cv2 which do not work without QT GUI.  On 4.1.1.26 cv2.getBuildInformation():

  GUI: 
    QT:                          YES (ver 4.8.7 EDITION = OpenSource)
      QT OpenGL support:         NO
    Cocoa:                       YES
    VTK support:                 NO

Is there something I need to do for QT to be enabled or is this related to the other QT issues?  I am wondering if anyone else is seeing this on MacOS as well

**Comment by skvark** [comment]
Qt should be enabled in the macOS builds (Qt 5.13). This thread tracks specific issue with Qt 5.15 which has been solved by not using version 5.15. Post the output of ``cv2.getBuildInformation()`` for 4.4.0.42. Enabling Qt in locally built packages requires that you have Qt development libraries installed on your system.

**Comment by mshabunin** [comment]
Package 4.4.0.42 uses Qt:
```
General configuration for OpenCV 4.4.0 =====================================
  Version control:               4.4.0-dirty

  Platform:
    Timestamp:                   2020-08-16T22:55:22Z
    Host:                        Darwin 17.7.0 x86_64
    CMake:                       3.18.0
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release
...
  GUI:
    QT:                          YES (ver 5.13.2)
      QT OpenGL support:         NO
    Cocoa:                       YES
    VTK support:                 NO
```
```
$ pip freeze
certifi==2020.6.20
numpy==1.19.1
opencv-python==4.4.0.42
```

**Comment by skvark** [comment]
Thanks @mshabunin!

@jdifran Please check that you are actually using the correct pre-built package / your environment is consistent. It's highly unlikely that I could fix the issue you are having in this repository.

**Comment by jdifran** [comment]
Thanks @skvark and @mshabunin , I am assuming this is due to being on an older macOS version (10.12) and Xcode 9 where QT5 requires per their support docs:

macOS 10.13, 10.14, 10.15 | x86_64 and x86_64h | Xcode 11 (10.15 SDK)

Is this just a case of QT getting excluded during the install due to the wrong platform requirements?  I notice I see this with other versions of opencv-python (4.3) besides the ones that include QT 4.8.7.  I am assuming this is a user requirements issue as this point which is why it works in 4.1.1.26

**Comment by skvark** [comment]
Qt is always included in the **pre-built** non-headless packages (`pip install opencv-python` or `pip install opencv-contrib-python`), it does not get magically excluded during install from those packages.

The latest **pre-built wheels** have minimum requirement of macOS 10.13 (see: https://github.com/skvark/opencv-python#backward-compatibility). 

Therefore, I believe that your problem is that `pip` has compiled OpenCV manually from the newly introduced source distribution because your system is not compatible with the pre-built packages. CMake just didn't find Qt from your machine, because it probably isn't there or if it is, you need to add additional flags for CMake before the build: https://github.com/skvark/opencv-python#manual-builds

Easiest way to fix this would of course to upgrade to latest macOS version. Otherwise you will have to learn how to configure OpenCV build system and build OpenCV manually.

**Comment by skvark** [comment]
The most recent release (4.5.1.48) drops Qt support on macOS. If you need Qt support, consider contributing.

**Comment by xgfd** [comment]
@skvark Just encountered this issue on macOS. As I understand you need to figure out a way copying the Info.plist file to the packages. Could you elaborate and I'll see whether I could help. Thanks.

**Comment by skvark** [comment]
4.4.0.40 is the only build that has this issue. The latest packages do not have Qt so you should not encounter the issue anymore. However, if you need Qt and want to help to add it back to the packages, then you can help by looking into the `Info.plist` file.

I'm not familiar with macOS software packaging requirements, so I can't help much. All I know is that Qt probably has the `Info.plist` file somewhere and I guess it should be next to the shared libraries inside the wheel packages. You can get Qt 5.15 via Homebrew, find the file and add it to the 4.4.0.40 install location. After that you can try to use `imshow`. If it crashes, the file is in the wrong place. But again, I'm just making guesses here.

**Comment by xgfd** [comment]
Both Qt5 and PyQt has a `lib` folder in parallel with the `plugins` folder, which has the following structure:
![image](https://user-images.githubusercontent.com/4529752/104921615-7c91ec00-5991-11eb-9cb5-c6a5571e0377.png)

So I did the obvious thing to copy `lib/QtCore.framework` (and later the whole `lib`) to `site-packages/cv2/qt` to create the following structure:

![image](https://user-images.githubusercontent.com/4529752/104921950-f4601680-5991-11eb-927d-3567982f45ac.png)

Unfortunately it didn't work. lldb gave the same traces as before. I'll poke around but honestly I don't have a clue right now. Is there a way to tell Qt where to look for those files? Or how does Qt look for these files?

**Comment by skvark** [comment]
Here you can find the link to relevant parts in Qt's source: https://github.com/opencv/opencv/issues/18079#issuecomment-673638205

Apple's docs: https://developer.apple.com/documentation/corefoundation/cfbundle?language=objc#overview

**Comment by skvark** [comment]
Here Qt tries to search for a bundle named `org.qt-project.QtCore`: https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qlibraryinfo.cpp#n494

This might be also relevant: https://developer.apple.com/documentation/corefoundation/1537085-cfbundlegetmainbundle?language=objc (https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qlibraryinfo.cpp#n194)

**Comment by xgfd** [comment]
Yeah went through those links but it's quite hard to figure out what's going on by just looking at source. I also tried setting os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] to the system Qt5 installation but got the same error.  Will keep looking.

**Comment by skvark** [comment]
I believe that the QT_QPA_PLATFORM_PLUGIN_PATH and the qt plugins folder is not relevant in this case. QtCore shared lib is trying to load the macOS bundle from somewhere, maybe directly next to the QtCore shared library. On Linux they are located in here: `site-packages/opencv_python.libs/`, maybe the place is similar on macOS.

**Comment by skvark** [comment]
Another thing to try is to place the bundle / file directly next to the `cv2.so`.

**Comment by xgfd** [comment]
On macOS there are only `cv2` and `opencv_python-4.4.0.40.dist-info` inside `opencv_python-4.4.0.40-cp38-cp38-macosx_10_13_x86_64.whl` and `site-packages`.  I'll try placing it next to the so file.

**Comment by xgfd** [comment]
Tried various locations following macOS bundle structures [Applications](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1), [Frameworks](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html#//apple_ref/doc/uid/20002253-BAJEJJAB) and [Loading Bundles](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingCode/Tasks/LoadingBundles.html#//apple_ref/doc/uid/20001273-CJBDDCAB), and [Qt docs](https://doc.qt.io/qt-5/macos-deployment.html), but with no luck. The cv2 package doesn't look like any apple bundle (changing the cv2/qt folder to Contents to mimic an application bundle didn't work either), which in the case of PyQt it resembles a Framework.

Then I came across this article [Qt is relocatable](https://www.qt.io/blog/qt-is-relocatable), where it states that you can turn off this relocation feature
![image](https://user-images.githubusercontent.com/4529752/104941926-a7893980-59ab-11eb-818e-1050ab96ad96.png)
. Can/Should this be done during the building process of opencv-python?

**Comment by skvark** [comment]
It requires full rebuild of Qt. It might help, but too much work to maintain separate build and it would take ages to build in the CI pipeline.

This comment in the Qt sources indicates that the Bundle location is relative to the QtCore shared library: https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qlibraryinfo.cpp#n487

Which means in practice that the `Resources/Info.plist` should be probably under `.dylibs` folder which is inside the wheels. I don't know where that folder is placed during install, but I would guess it similar to Linux: `site-packages/opencv_python.dylibs/`

**Comment by xgfd** [comment]
Placing plist directly under .dylibs or .dylibs/Resources didn't work. Found [this link](https://github.com/mixxxdj/buildserver/pull/86) and related [discussions](https://bugs.launchpad.net/mixxx/+bug/1871238). Seemed relevant since we're shipping Qt without frameworks too.

**Comment by skvark** [comment]
It seems that the only solution is to use a custom Qt build. That would require some custom repository to build and package it as a Homebrew bottle for example. Qt cannot be built as a part of the current build pipelines since it is such a large and heavy project.

**Comment by asmorkalov** [comment]
The most recent release (4.5.1.48) drops Qt support on macOS and should fix this issue.

**Comment by asmorkalov** [comment]
Related issue: https://github.com/opencv/opencv-python/issues/423

**Comment by asmorkalov** [comment]
Tested with OpenCV-Python 4.5.1, works without issues.
