### ISSUE TITLE
Get rid of the macOS caching stage

### ISSUE THREAD

**Issue by skvark** [opencv/opencv-python#421]
The macOS caching stage which currently builds LGPL version of FFmpeg needs to be refactored away as the repository transitions away from Travis.

Probably the best possible solution is to separate the FFmpeg homebrew bottle build code to another repository. Then we can just install the pre-built bottle with homebrew in macOS builds similarly to the Qt 5.13 bottle.

**Comment by skvark** [comment]
It seems that the macOS builds can be completed currently without the caching stage. However, it would be nice to have pre-built FFmpeg for faster builds.

**Comment by asmorkalov** [comment]
Done during migration to Github Actions.
