### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/surbhi/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.

### ISSUE THREAD

**Issue by surbhi1986** [opencv/opencv-python#447]
Hi I was using mmdetection for custom data, after training i saved the model.
But during testing on single image i am getting error during show which is given please. Please help guys.

QObject::moveToThread: Current thread (0x3d9b720) is not the object's thread (0x5af24f0).
Cannot move to target thread (0x3d9b720)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/surbhi/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Aborted (core dumped)

**Comment by asmorkalov** [comment]
The error message means that OpenCV cannot initialize UI session, e.g. the program started over SSH without X forwarding.

**Comment by asmorkalov** [comment]
Also please check this thread: https://forum.qt.io/topic/119109/using-pyqt5-with-opencv-python-cv2-causes-error-could-not-load-qt-platform-plugin-xcb-even-though-it-was-found

**Comment by skvark** [comment]
There is most likely a conflicting Qt installation somewhere. Installing `opencv-python-headless` instead of `opencv-python` usually fixes this. If GUI features are needed (`imshow`), then the conflicting Qt (such as PyQt) needs to be removed.

**Comment by shuang1204** [comment]
我安装完opencv-python-headless，又出现了新的问题，cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-tk9iuyva/opencv/modules/highgui/src/window.cpp:634: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow
'请问该怎么解决呀@Olli-Pekka Heinisuo skvark

**Comment by asmorkalov** [comment]
@shuang1204  opencv-python-headless is OpenCV version built *without* UI support and "The function is not implemented" exception is designed behavior. Use opencv-python package, if you need UI support.

**Comment by swetapandey-12** [comment]
Error is solve but what if we  import cv2 for futher use , it showing module not found
