### ISSUE TITLE
Segmentation fault for matplotlib and open-cv

### ISSUE THREAD

**Issue by meteoDaniel** [opencv/opencv-python#449]
I am receiving the same segmentation fault that is mentioned here in https://github.com/opencv/opencv-python/issues/381  for python3.8 as well for 3.9. 
```
Thread 0x00007f348fa15740 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/matplotlib/font_manager.py", line 997 in json_dump
  File "/usr/local/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1425 in _rebuild
  File "/usr/local/lib/python3.9/site-packages/matplotlib/font_manager.py", line 1431 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
.
.
.
```

This is my requirements.txt:
```
numpy==1.20.1
scipy==1.6.0
netCDF4==1.5.6
pandas==1.2.2
opencv-contrib-python==4.5.1.48
imutils==0.5.4
xarray==0.16.2
ffmpeg==1.4
ipython==7.10.1
ipython-genutils==0.2.0
trackpy==0.4.2
Shapely==1.7.1
geopandas==0.8.2
descartes==1.1.0
SQLAlchemy==1.3.13
psycopg2-binary==2.8.6
h5netcdf==0.10.0
h5py==3.1.0
pytest==6.1.0
multidict==4.7.6
yarl==1.6.0
aiohttp==3.7.3
wradlib==1.9.0
wetterdienst==0.14.0
requests==2.25.1
matplotlib==3.3.4
``` 
My base image `FROM python:3.9.1-slim`
I hope anyone can help.

**Comment by skvark** [comment]
A minimum reproducible example would help a lot. There are quite many dependencies, are you sure the issue is related to opencv-python?

**Comment by meteoDaniel** [comment]
The problem is that the image builds GDAL and I do not want to annoy you by building an image with GDAl (takes approx. 45 min). 

But I solved this by adding 
`RUN apt-get install -yqq python3-opencv`
before. 
I do not know why. Maybe this helps you to improve the package.
