### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'cvtColor'

### ISSUE THREAD

**Issue by LeiChangxin** [opencv/opencv-python#456]
"x = cv2.cvtColor(np.array(image,np.float32)/255, cv2.COLOR_RGB2HSV)"

When I run the code to the line above,the AttributeError occur.I have checked the package of cv2,but I don't find the module "cvtColor".But according to the introduction of cv2,it contains the module "cvtColor".I want to know what I can do to solve the problem.Thank you for your instruction

opencv-python version：opencv-python-4.5.1.48
opencv-contrib-python version：opencv-contrib-python-4.5.1.48

**Comment by Ankuraxz** [comment]
Hoping that you have correctly installed opencv-python. This error should not occur, as far as "image" is an RGB Image. I tried it with an RBG Image and the following OpenCV package. If not needed you can uninstall opencv-contrib and reinstall opencv-python with `pip install opencv-python==4.5.1.48`

[If you are using Ubuntu OS, you may need to install a few other packages](https://stackoverflow.com/a/67088720/9782747)


```
Name: opencv-python
Version: 4.5.1.48
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: None
Author-email: None
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: numpy
Required-by: 

```

**Comment by sanketc001** [comment]
is this issue solved? if so plz close the thread

**Comment by Ankuraxz** [comment]
It's close, as far as I can see, it was just some installation issue

**Comment by gaurav00700** [comment]
@LeiChangxin make sure you have used `cvtColor` not `cvtcolor` .
