### ISSUE TITLE
Prepare release OpenCV 4.5.2

### ISSUE THREAD

**Issue by asmorkalov** [opencv/opencv-python#459]
### Expected behaviour

Write here how did you expect the library to function.

### Actual behaviour

Write here what went wrong.

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by sergregory** [comment]
Should be fixed with the #470

**Comment by johnnnya** [comment]
cv2.barcode_BarcodeDetector()

**Comment by mengfu188** [comment]
`cv2.wechat_qrcode_WeChatQRCode`
code in [https://github.com/opencv/opencv_contrib/blob/master/modules/wechat_qrcode/src/wechat_qrcode.cpp#L156](https://github.com/opencv/opencv_contrib/blob/master/modules/wechat_qrcode/src/wechat_qrcode.cpp#L156)
doc in [https://docs.opencv.org/master/d5/d04/classcv_1_1wechat__qrcode_1_1WeChatQRCode.html](https://docs.opencv.org/master/d5/d04/classcv_1_1wechat__qrcode_1_1WeChatQRCode.html)
blog in [https://mp.weixin.qq.com/s/AknsKNqVmvr8aohV25_ZcQ](https://mp.weixin.qq.com/s/AknsKNqVmvr8aohV25_ZcQ)

**Comment by johnthagen** [comment]
This has been released on PyPI: https://pypi.org/project/opencv-python/4.5.2.52/

**Comment by williamjacksn** [comment]
I figured it out. The release workflow builds the sdist but doesn't upload it. The step that uploads the files to PyPI looks for files that match `opencv_python-*` but the built file is named `opencv-python-4.5.2.52.tar.gz`. Notice the hyphen instead of the underscore.

**Comment by skvark** [comment]
I think @sergregory or someone else can upload the source distributions manually to PyPI. The source tarballs should be available in the Github Actions artifact storage.
