### ISSUE TITLE
xfeatures2d not found

### ISSUE THREAD

**Issue by aaryan-sarawgi1** [opencv/opencv-python#460]
`detector = cv2.xfeatures2d.SURF_create(hessianThreshold, nOctaves, nOctaveLayers, extended, upright)` in eyeDetect.py file
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'.

This is the steps I followed from https://github.com/LukeAllen/optimeyes
```git clone --recursive https://github.com/opencv/opencv-python.git
cd opencv-python
export CMAKE_ARGS="-DOPENCV_ENABLE_NONFREE=ON"
export ENABLE_CONTRIB=1
python setup.py bdist_wheel
pip install dist/opencv_contrib_python-x.x.x.x.whl```

 - The issue is related to the build scripts in this repository, to the pre-built binaries 
 - I'm using the latest version of opencv-python

**Comment by asmorkalov** [comment]
Please provide `cv.getBuildinformation()` call output to ensure that you use self-built OpenCV package with NONFREE enabled.

**Comment by aaryan-sarawgi1** [comment]
`General configuration for OpenCV 4.5.1 =====================================
  Version control:               4.5.1

  Platform:
    Timestamp:                   2021-04-07T08:48:53Z
    Host:                        Windows 10.0.19042 AMD64
    CMake:                       3.18.4
    CMake generator:             Ninja
    CMake build tool:            C:/PROGRA~2/MICROS~3/2017/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe
    MSVC:                        1916
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2
      requested:                 SSE2
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX
      requested:                 SSE4_1 SSE4_2 AVX FP16
      SSE4_1 (15 files):         + SSE3 SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 AVX

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe  (ver 19.16.27045.0)        
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS  /arch:SSE /arch:SSE2 /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589  /MT 
/O2 /Ob2 /DNDEBUG
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS  /arch:SSE /arch:SSE2 /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589  /MTd /Zi /Ob0 /Od /RTC1
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS  /arch:SSE /arch:SSE2   /MT /O2 /Ob2 /DNDEBUG
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS  /arch:SSE /arch:SSE2 /MTd /Zi /Ob0 /Od /RTC1
    Linker flags (Release):      /machine:X86  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib   
    Linker flags (Debug):        /machine:X86  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib  
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          ade wsock32 comctl32 gdi32 ole32 setupapi ws2_32     
    3rdparty dependencies:       ittnotify libprotobuf zlib libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf quirc ippiw ippicv

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching video videoio
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 java python2 ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.0.6-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.0.10)
    JPEG 2000:                   build (ver 2.3.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.91.100)
      avformat:                  YES (58.45.100)
      avutil:                    YES (56.51.100)
      swscale:                   YES (5.7.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   C:/Users/Aaryan/Documents/GitHub/Eye Tracker/optimeyes/opencv-python/_skbuild/win32-3.8/cmake-build/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                C:/Users/Aaryan/Documents/GitHub/Eye Tracker/optimeyes/opencv-python/_skbuild/win32-3.8/cmake-build/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (NVD3D11)
    Include path:                C:/Users/Aaryan/Documents/GitHub/Eye Tracker/optimeyes/opencv-python/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 C:/Program Files (x86)/Python38-32/python.exe (ver 3.8.1)
    Libraries:                   C:/Program Files (x86)/Python38-32/libs/python38.lib 
(ver 3.8.1)
    numpy:                       C:/Users/Aaryan/AppData/Roaming/Python/Python38/site-packages/numpy/core/include (ver 1.18.3)
    install path:                python

  Python (for build):            C:/Program Files (x86)/Python38-32/python.exe        

  Java:
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    C:/Users/Aaryan/Documents/GitHub/Eye Tracker/optimeyes/opencv-python/_skbuild/win32-3.8/cmake-install`

**Comment by skvark** [comment]
**Non-free algorithms: NO** 

I see you are using Windows but following a Linux guide. There is no such thing as `export` on Windows.

Command line:

`set CMAKE_ARGS="-DOPENCV_ENABLE_NONFREE=ON"`

Powershell:

`$Env:CMAKE_ARGS="-DOPENCV_ENABLE_NONFREE=ON"`

**Comment by aaryan-sarawgi1** [comment]
Thanks a lot , i tried SET in PS and it didnt work , but doing it in cmd after a fresh reinstallation worked.

**Comment by aaryan-sarawgi1** [comment]
Thanks a lot. I tried `SET` in ps but it didnt work but using it in cmd worked 
Also I am getting this error while using this to try to access the webcam. If anyone can help it would be nice.
 ```WARN:0] global C:\Users\Aaryan\Documents\GitHub\Eye Tracker\optimeyes\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (434) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File "eyeDetect.py", line 724, in <module>
    main()
  File "eyeDetect.py", line 650, in main
    raise(Exception("failed to open camera."))
Exception: failed to open camera.```

**Comment by abhiTronix** [comment]
@aaryan-sarawgi1 Try using backend `CAP_DSHOW` instead, as `cv2.VideoCapture(0, cv2.CAP_DSHOW)`.

**Comment by aaryan-sarawgi1** [comment]
Thanks a lot .It had `cv2.VideoCapture(1)` for default camera but I am not sure why it was not opening
