### ISSUE TITLE
cv2 imshow error

### ISSUE THREAD

**Issue by Judfruit** [opencv/opencv-python#462]
### Expected behaviour

show the image

### Actual behaviour

error :raceback (most recent call last):
  File "/Users/justine/Desktop/TIPE/test.py", line 3, in <module>
    cv2.imshow('Window',img)
cv2.error: OpenCV(4.5.1) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-39p1qqfs/opencv/modules/highgui/src/window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'

But no error when line 3 is commented, it seems to load correctly the image.

### Steps to reproduce

import cv2
img=cv2.imread('Lune2.jpg')
cv2.imshow('Window',img)
cv2.waitKey(0)

**Comment by skvark** [comment]
This is not a bug, your image is just empty as the error indicates. Check that the file path is correct. In the future, please ask common usage and programming related questions at https://forum.opencv.org/.

**Comment by yoyojacky** [comment]
![image](https://user-images.githubusercontent.com/6893075/161287426-8db8921b-63cd-4247-a661-c4c0c1c770c2.png)
![image](https://user-images.githubusercontent.com/6893075/161287516-6990e75c-13c9-47be-a9af-d5702dcedf87.png)
what can i do ?  i have already installed libgtk2.0-dev and pkg-config package via `sudo apt -y install libgtk2.0-dev pkg-config` in a terminal and it  still won't work. 
and  I have already reinstalled `opencv-python  opencv-contrib-python ` pacakge via ` pip install command .
