### ISSUE TITLE
Separate layer binary threshold

### ISSUE THREAD

**Issue by AryanSethi** [opencv/opencv-python#463]
I want to contribute to openCV-python to add a binary threshold function that works separately on each layer of an RGB image with  different threshold values.
Where and how can I get started ?

**Comment by skvark** [comment]
OpenCV code is written in C++ and developed in the main repository (https://github.com/opencv/opencv) and the contrib repository (https://github.com/opencv/opencv_contrib).

This repository builds the C++ code as a Python extension module and publishes binary packages to the Python package index. New features cannot be implemented here. 

You might want to start from here: https://github.com/opencv/opencv/wiki/How_to_contribute
