### ISSUE TITLE
Relax or update numpy version for python 3.8

### ISSUE THREAD

**Issue by mmgaggle** [opencv/opencv-python#464]
When using pipenv in a python 3.8 environment to install openvino-dev and tensorflow together [1], it results in a unresolvable dependency on numpy. 

tensorflow >=2.3 requires numpy >= 1.19.0 [2]
openvino-dev requires numpy ~=1.18.5 [3]
opencv-python rquires numpy  == 1.17.3 [4]

Would it be possible for opencv-python to either relax the version for python 3.8, or pin to a version >= 1.19?

I've already commented on openvino PR that introduced 1.18.5 [5]

[1] https://github.com/mmgaggle/s2i-openvino-notebook/blob/wip-python38/requirements.in#L11
[2] https://github.com/tensorflow/tensorflow/issues/41902
[3] https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/python/wheel/meta/openvino-dev.requirements.txt#L4
[4] https://github.com/opencv/opencv-python/blob/master/pyproject.toml#L7
[5] https://github.com/openvinotoolkit/openvino/pull/5013

**Comment by skvark** [comment]
`pyproject.toml` defines build-time dependencies. The runtime `numpy` version requirement is relaxed: https://github.com/opencv/opencv-python/blob/master/setup.py#L38

The other issues you linked seem to be referring to runtime requirements. You should be able to use any `numpy` version above 1.17.3 with `opencv-python` and Python 3.8.

Are you trying to build `opencv-python` from sources?

**Comment by mmgaggle** [comment]
You are right, this was a red herring. I had a conflict for numpy == 1.17.3 and it matched just so happened to match to what was in that build file. I'll have to do some work with pipenv graph to better understand where the conflict arises. Thanks for the quick response!
