### ISSUE TITLE
Incorrect co-ordinates format returned by minMaxLoc()

### ISSUE THREAD

**Issue by jadevaibhav** [opencv/opencv-python#465]
### Expected behaviour
the co-ordinates should be returned in (x,y) format.

Write here how did you expect the library to function.
The official tutorial and various others use the same format which returns wrong co-ordinate.
### Actual behaviour

Write here what went wrong.

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version : 4.1.2(Google Colab default version)

I have reproduced the behaviour here: https://colab.research.google.com/drive/1flZTSDaHdf0xkxI5vwJrnyhdO-b1McQX?usp=sharing.

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
@jadevaibhav Thanks for the report. It looks like the issue that you described related not to minMaxLoc, but the way matchTemplate works in OpenCV. matchTemplate returns heatmap and you can get several maximal values there. Most probably minMaxLoc found another optimal point. I checked matchTemplate tutorial in OpenCV and simple things with minMaxLoc and everything works properly:
```
>>> a = np.random.randint(255, size=(5, 5))
>>> a
array([[ 98, 142, 194, 219,  16],
       [100,  50, 124,  21,  25],
       [125, 223, 243, 168,  90],
       [241, 177,  47, 108, 163],
       [167, 235,  70, 239,  90]])
>>> cv.minMaxLoc(a)
(16.0, 243.0, (4, 0), (2, 2))
```

**Comment by jadevaibhav** [comment]
Thank you for your response.
For this particular array, the max is at (2,2) so it's the right result. For the min though, shouldn't it be (0,4)? I have also demonstrated the example for a sample image in the colab.

Please have a look.

**Comment by asmorkalov** [comment]
minMaxLoc returns cv::Point in C++ code. `cv::Point` has x and y coordinates inside, but not row and col. According to this logic in my sample x = 4, y = 0. So it works as designed.

**Comment by asmorkalov** [comment]
@jadevaibhav Do you have updates here?
