### ISSUE TITLE
CV2 installed, but when i Import cv2 on spyder it gives me this  error :     import cv2  ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by saida11000** [opencv/opencv-python#466]
Hi, i'm working with nvidia jetson nano (linux) , i installed opencv under linux but when i import cv2 with spyder it gives me this error : 
    import cv2

ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
i need help please ^^

**Comment by skvark** [comment]
https://github.com/opencv/opencv/issues/14884
