### ISSUE TITLE
Why does the flag set in cv2.calibrateCamera() not work?

### ISSUE THREAD

**Issue by Easonyesheng** [opencv/opencv-python#472]
### Expected behaviour

I want use the cv2.calibrateCamera() to calculate the camera intrinsic parameters using the flag like cv2.CALIB_FIX_FOCAL_LENGTH which works well in C++.

### Actual behaviour

The cv2.calibrateCamera() can take in the flag but just not work.
It must get something wrong in the API.

**Comment by asmorkalov** [comment]
@Easonyesheng Could you provide the issue reproducer and OpenCV version you use. Also please ensure that you have `CALIB_USE_INTRINSIC_GUESS` mentioned in flags, otherwise the function ignores provided focal length value.

**Comment by Easonyesheng** [comment]
@asmorkalov 
# My environment is as follow:
  python-opencv 3.4.2 
  python 3.6

# This issue appears in code like this:
```python
def __calibrate_with_flag(self, f, pp):
        """name
            Calibration with fix focal length
        Args:
            f: focal length
            pp: principle points
        Returns:
        """
        mtx = np.array([[f,0,pp],
                        [0,f,pp],
                        [0,0,1]])
        ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(self.object_points, self.img_points, (self.img.shape[2], self.img.shape[1]),cv2.CALIB_USE_INTRINSIC_GUESS,cv2.CALIB_FIX_FOCAL_LENGTH)
        return ret, mtx, dist, rvecs, tvecs
```
This code doesn't work like calibration with fix focal length and it just ignores the two flags I set.
I'm not sure it is the right way to provide focal length cause I cannot find related reference documents.

**Comment by asmorkalov** [comment]
I see 2 issues in the provided code:

**Comment by Easonyesheng** [comment]
Thank you!
I will check these 2 issues.
