### ISSUE TITLE
unable to import opencv-contrib-python-asenyaev 4.5.2, cant open (truncated) so

### ISSUE THREAD

**Issue by miba2020** [opencv/opencv-python#474]
https://pypi.org/project/opencv-contrib-python-asenyaev/ link to this repository

### Expected behaviour

import cv2 without exception

### Actual behaviour

>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/renlifeng/wechat/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libpng15-c2ffaf3d.so.15.13.0: cannot open shared object file: No such file or directory
>>> 

### Steps to reproduce

- example code: pip install opencv-contrib-python-asenyaev
- operating system: ubuntu 18.04
- architecture: amd64
- opencv-python 4.5.2

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by miba2020** [comment]
- setting LD_LIBRARY_PATH does not help
- ldd cv2.cpython-36m-x86_64-linux-gnu.so said multiple so not found
     libpng15-c2ffaf3d.so.15.13.0 => not found
- cp these .so to /usr/local/lib, and run ldconfig. get complains like:
       /sbin/ldconfig.real: file /usr/local/lib/libavcodec-8daa01ff.so.58.109.100 is truncated

**Comment by skvark** [comment]
That's not an official package.

**Comment by mengfu188** [comment]
When will 4.5.2 be released? I want to use [https://github.com/opencv/opencv_contrib/blob/master/modules/wechat_qrcode/src/wechat_qrcode.cpp#L156](https://github.com/opencv/opencv_contrib/blob/master/modules/wechat_qrcode/src/wechat_qrcode.cpp#L156)

**Comment by miba2020** [comment]
Sorry. Actually, I had hesitated for a while before filing this report.

By the way, when will version 4.5.2 be ready?

**Comment by miba2020** [comment]
thanks! looking forward to your 4.5.2 release plan.

**Comment by skvark** [comment]
Please follow this issue for updates on 4.5.2: https://github.com/opencv/opencv-python/issues/459
