### ISSUE TITLE
How to speed up make.

### ISSUE THREAD

**Issue by mengfu188** [opencv/opencv-python#481]
### Expected behaviour

Write here how did you expect the library to function.
I use `pip wheel . --verbose`. In make progress, it seems use one cpu core. How to set multi cpu?

### Actual behaviour

Write here what went wrong.

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
If you are on Linux, maybe `export MAKEFLAGS=-j$(nproc)` helps?

**Comment by mengfu188** [comment]
I use `export MAKEFLAGS=-j40`. It worked nice. Thank you.
