### ISSUE TITLE
ORB Demo code errors out with cv2.error: Unknown C++ exception from OpenCV code

### ISSUE THREAD

**Issue by WurmD** [opencv/opencv-python#486]
### Expected behaviour
Demo code from https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_orb/py_orb.html
```
import cv2
img = cv2.imread('images/IMG_6769.jpg',0)
orb = cv2.ORB()
kp = orb.detect(img,None)

```
should run

### Actual behaviour

`cv2.error: Unknown C++ exception from OpenCV code`

### Steps to reproduce

- example code: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_orb/py_orb.html
- operating system: Windows 10
- architecture (e.g. x86): x64
- opencv-python version: 4.5.2.52

### Extras
OpenCV Issue: https://github.com/opencv/opencv/issues/20081 
Stackoverflow: https://stackoverflow.com/questions/67526521/orb-demo-code-errors-out-with-cv2-error-unknown-c-exception-from-opencv-code

**Comment by asmorkalov** [comment]
The issue has been resolved in the related OpenCv issue.

**Comment by studystudyismyname** [comment]
hi,i'm also a beginner. Have you solved this problem.I searched this problem for several days and found no result.I don't know where going wrong.If you solve this problem, would you please tell me why. Thank you!
