### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('opencv-python==4.1.0.25')

### ISSUE THREAD

**Issue by neni1705** [opencv/opencv-python#487]
I am using the lates version of opencv-python but when I run  python setup.py develop in lvis-api/ directory I got this error

$ python setup.py develop
running develop
running egg_info
writing lvis.egg-info\PKG-INFO
writing dependency_links to lvis.egg-info\dependency_links.txt
writing requirements to lvis.egg-info\requires.txt
writing top-level names to lvis.egg-info\top_level.txt
reading manifest file 'lvis.egg-info\SOURCES.txt'
writing manifest file 'lvis.egg-info\SOURCES.txt'
running build_ext
Creating c:\users\user\appdata\local\programs\python\python39\lib\site-packages\lvis.egg-link (link to .)
lvis 0.5.1 is already the active version in easy-install.pth

Installed d:\kumamoto university\72475-image information processing\balance softmax\balancedgroupsoftmax-master\balancedgroupsoftmax-master\lvis-api
Processing dependencies for lvis==0.5.1
Searching for opencv-python==4.1.0.25
Reading https://pypi.org/simple/opencv-python/
No local packages or working download links found for opencv-python==4.1.0.25
error: Could not find suitable distribution for Requirement.parse('opencv-python==4.1.0.25')

could you help me to solve this problem?

**Comment by sergregory** [comment]
What are your pip version and python version? Pip has changed its resolving mechanism, it may be the case if you do not use the latest version
