### ISSUE TITLE
how to use opencv to open webcam

### ISSUE THREAD

**Issue by Tan-Kwee-Khuang-alice** [opencv/opencv-python#494]
### Expected behaviour

Write here how did you expect the library to function.

### Actual behaviour

Write here what went wrong.

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by Tan-Kwee-Khuang-alice** [comment]
Hi there,

is there example code to open the webcam using opencv

**Comment by NeilRoy678** [comment]
the following will open the webcam using OpenCV

```
import cv2
cap = cv2.VideoCapture(0)

while True:
    ret,frame = cap.read()
    cv2.imshow('WEBCAM',frame)

    if cv2.waitKey(1) & 0xFF == ord('a'):
        break
cap.release()
cv2.destroyAllWindows()
```
 
OS: Windows 10
a version of OpenCv:4.5.2.52
