### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2' in PyCharm

### ISSUE THREAD

**Issue by alex27riva** [opencv/opencv-python#495]
Hi everyone, I get the following error in PyCharm Community 2021.1:

```
 import cv2
ModuleNotFoundError: No module named 'cv2'
```
Terminal inside PyCharm:
![Pycharm terminal](https://i.ibb.co/7JTLY8m/cv2-issue.png)

I'm using the latest version of opencv-python on Linux Pop!_OS 20.04, Python 3.8.
The package is installed under a virtual environment (venv) in PyCharm.

I tried some solution on various forums, but I have not solved yet.

**Comment by VictorBebnev** [comment]
Hi @alex27riva,
Probably, your pip is not connected with your venv. Pip is used from the system, not from venv.
Could you try to use pip as a python module?

Try this:
```
python -m pip install opencv-python
python -m pip list | grep "opencv"
python -c 'import cv2; print(cv2.__version__);
```

**Comment by knackmanic** [comment]
cd to the venv path and do what @VictorBebnev suggests using a command line. You'll probably also get a prompt to update pip. This workaround has fixed multiple issues I had with module installation in pycharm.

**Comment by asmorkalov** [comment]
@alex27riva Have you tried the solution?

**Comment by asmorkalov** [comment]
@alex27riva I close the issue as there is no response. Please reopen the ticket if the solution does not work and you have more details.

**Comment by mihaker331** [comment]
tema ne zakrita
