### ISSUE TITLE
no NvidiaOpticalFlow

### ISSUE THREAD

**Issue by EBGU** [opencv/opencv-python#499]
### Expected behaviour

I am using Navidia optical flow following this demo: https://developer.nvidia.com/blog/opencv-optical-flow-algorithms-with-nvidia-turing-gpus/

### Actual behaviour
However, with nvof = cv2.cuda_NvidiaOpticalFlow_1_0.create(frame1.shape[1], frame1.shape[0], 5, False, False, False, 0), I got an error:

AttributeError: module 'cv2.cv2' has no attribute 'cuda_NvidiaOpticalFlow_1_0'

### Steps to reproduce

I am using custom compiled opencv with cuda on:

cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D WITH_CUDA=ON \
        -D ENABLE_FAST_MATH=1 \
        -D CUDA_FAST_MATH=1 \
        -D WITH_CUBLAS=1 \
	-D PYTHON3_EXECUTABLE=$CONDA_ENV_PATH/$CONDA_ENV_NAME/bin/python \
	-D INSTALL_C_EXAMPLES=ON \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D OPENCV_EXTRA_MODULES_PATH=$WHERE_OPENCV_CONTRIB/modules \
	-D BUILD_EXAMPLES=ON $WHERE_OPENCV
	-D PYTHON3_PACKAGES_PATH=$CONDA_ENV_PATH/$CONDA_ENV_NAME/lib/python3.6/site-packages \
	-D BUILD_opencv_python2=OFF \
        -D BUILD_opencv_python3=ON \

Following related item could be found:

/usr/local/lib/libopencv_cudaoptflow.so.4.5.2
/usr/local/lib/libopencv_cudaoptflow.so.4.5
/usr/local/lib/libopencv_cudaoptflow.so
/usr/local/include/opencv4/opencv2/cudaoptflow.hpp
/usr/local/share/opencv4/samples/cudaoptflow/nvidia_optical_flow.cpp
/usr/local/share/opencv4/samples/cudaoptflow/optical_flow.cpp

And following cuda modules could be found with python:
        cv2.cuda_BufferPool
        cv2.cuda_DeviceInfo
        cv2.cuda_Event
        cv2.cuda_GpuMat
        cv2.cuda_GpuMat_Allocator
        cv2.cuda_HostMem
        cv2.cuda_Stream
        cv2.cuda_TargetArchs

The Nvidia optical flow SDK was compiled already.
##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Optical flow is dedicated module in OpenCV Contrib. Please check your OpenCV build options with `print(cv2.getBuildInformation())`. I use pre-built OpenCV installed with Pypi (pip) It's built without CUDA support and Optical Flow module is in list of unavailable modules:
```
General configuration for OpenCV 4.5.2 =====================================
...
  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core cvv datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 alphamat cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev freetype hdf java julia matlab ovis python2 sfm ts viz
...
```

**Comment by asmorkalov** [comment]
The ticket has been closed, because Pypi distro does not support CUDA for now.  opencv-python and  opencv-python-contrib packages are self contained and use internal version OpenCV. So `/usr/local/lib/libopencv_cudaoptflow.so.4.5` are not used if you install OpenCV with pip.
