### ISSUE TITLE
imshow core dump

### ISSUE THREAD

**Issue by WolfgangFahl** [opencv/opencv-python#501]
### Expected behaviour

calling cv2.imshow(title,image) should never lead to a  core dump

### Actual behaviour

There is a core dump

### Steps to reproduce

see https://github.com/WolfgangFahl/play-chess-with-a-webcam/issues/36
- operating system: Ubuntu 20
- opencv-python version  - multiple - just trying to catch up with compatibility. 4.4.0.46, 4.3.0.38 definitly fail

**Comment by WolfgangFahl** [comment]
4.5.2.54 also fails

**Comment by WolfgangFahl** [comment]
see also

- https://stackoverflow.com/questions/60678048/segmentation-fault-after-cv2-imshowwinname-mat

**Comment by WolfgangFahl** [comment]
seems not be OS dependend. See https://github.com/WolfgangFahl/play-chess-with-a-webcam/actions/runs/931645670

**Comment by asmorkalov** [comment]
OpenCV uses GTK or QT as backend for window management on Linux. Both require correct X server session to create a window and do rendering. Github Actions as soon as most of CI systems does not manage X sessions and the `imshow` fails. Headless build of OpenCV presumes UI related API for API compatibility, but raises exception, if imshow is called.

Options:
- Do not use `imshow` in tests.
- Run X sever and manage it manually in CI scripts. XVFB project works the best with CI.

**Comment by WolfgangFahl** [comment]
I understand the circumstances and still think there should not be a core dump but e.g. a message that the X-Server ist not reachable.

**Comment by WolfgangFahl** [comment]
In my case i had to awkwardly work around this and check the headless state to avoid calling imshow.

**Comment by asmorkalov** [comment]
OpenCV throws exception, if it gets control with error code. So nothing could be done here.
