### ISSUE TITLE
imencode with headless version 

### ISSUE THREAD

**Issue by weiweilars** [opencv/opencv-python#503]
### Expected behaviour

imencode function can be used in opencv-python-headless

### Actual behaviour

imencode does not work with headless version

**Comment by asmorkalov** [comment]
@weiweilars Please provide code to reproduce the issue, OpenCV version you use and image itself. Particular image format support depends on OpenCV build options and 3rd-party libraries.

**Comment by asmorkalov** [comment]
@weiweilars Do you have any update on this?

**Comment by asmorkalov** [comment]
Closed as incomplete.
