### ISSUE TITLE
LBPHFaceRecognizer recognizer not returning correct label when label is big integer (about 18 digits)

### ISSUE THREAD

**Issue by ProgrammingPlanet** [opencv/opencv-python#513]
### Expected behaviour

in the training phase, i assigned a integer label 983993829563581248 to an image, in recognition phase recognizer.predict() must return 983993829563581248 as label.

### Actual behaviour

recognizer.predict() returning label 1843000098, which is even not the label of any available image.

### other info

opencv-python==4.5.2.54
opencv-contrib-python==4.5.2.54
os = windows 10
arch - 64 bit

**Comment by asmorkalov** [comment]
OpenCV uses 32-bit integer for labels. The issue you observe is typical integer overflow. The only way to fix it is to reduce labels range.
