### ISSUE TITLE
from .cv2 import * E   ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by dickreuter** [opencv/opencv-python#514]
I'm trying to install opencv on travis on github, but it seems a dll is missing when I import cv2. Is there any way to install it for travis on windows?

https://app.travis-ci.com/github/dickreuter/Poker/builds/231980314

The error is as follows:

```
    import cv2
c:\python37\lib\site-packages\cv2\__init__.py:5: in <module>
    from .cv2 import *
E   ImportError: DLL load failed: The specified module could not be found.
```

**Comment by asenyaev** [comment]
Hi @dickreuter!

Could you try to reproduce this issue with the latest opencv-python version (`opencv-python==4.5.4.60`)?
