### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by mluerig** [opencv/opencv-python#519]
not an issue - but how should we cite opencv-python, if we use it in our own modules and publish those? I have cited the OpenCV library, but opencv-python is a specific variant that could be referenced.

**Comment by asmorkalov** [comment]
Related: https://github.com/opencv/opencv/wiki/CiteOpenCV

**Comment by asenyaev** [comment]
@alalek @vpisarev, what do you think about opencv-python citing? Could it be something like the pattern below?
```
@software{opencv-python,
  author = {Olli-Pekka, Heinisuo and OpenCV, team},
  month = {9},
  title = {{OpenCV Python packages}},
  url = {https://github.com/opencv/opencv-python},
  year = {2016}
}
```
A month and a year are about the first OpenCV python packages release.

In addition, I would suggest to add it in wiki and in `CITATION.cff` file in the repository, or only in one place. Also, maybe it would be good to add `CITATION.cff` file in opencv repository too ([docs about citing](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)).

**Comment by asmorkalov** [comment]
@skvark Your opinion?

**Comment by skvark** [comment]
That looks ok to me. Note that in BibTeX format the family name and given name should be the other way around: `author = {Heinisuo, Olli-Pekka and team, OpenCV}`. 

It would be good to include the CITATION.cff files in the repositories, Github will then autogenerate the correct citation files.

**Comment by asmorkalov** [comment]
The proposal was discussed on core OpenCV meeting with @alalek @vpisarev @asenyaev @rogday @AleksandrPanov  and others. The team decided that there is no much sense to add dedicated citing to the opencv-python reposity as it does not contain bindings for Python or other CV functionality. Please use core repo for citing. The team looks foward on citing block update for OpenCV 5.0 release, if some  whitepaper or technical report is released for it.
