### ISSUE TITLE
Does OpenCV VideoWriter use FFmpeg? How does it handle compression or other options?

### ISSUE THREAD

**Issue by sofakng** [opencv/opencv-python#521]
I'm trying to understand how OpenCV VideoWriter works but I'm a bit confused.

Does it use FFmpeg to write/create videos?  If so, how does it handle compression?

You can specify the FOURCC codec but I don't see any options for compression, H264/H265 CRF value, etc?

**Comment by asmorkalov** [comment]
OpenCV does not expose FFmpeg/GStreamer/MSMF compression options as public API. The only option for now that you can manage is bitrate.

**Comment by sofakng** [comment]
Got it.  Thanks for the information!

**Comment by 0xiNach** [comment]
> OpenCV does not expose FFmpeg/GStreamer/MSMF compression options as public API. The only option for now that you can manage is bitrate.

How can you set bitrate?
