### ISSUE TITLE
VideoCapture Not Found

### ISSUE THREAD

**Issue by Rpal1315** [opencv/opencv-python#523]
### Expected behaviour

Expected it to have VideoCapture

### Actual behaviour

When using in PyCharm and declaring cv2.VideoCapture after importing it is showing a error that VideoCapture is not found _init_.py

### Steps to reproduce

Code
```
import cv2
cam = cv2.VideoCapture(0)
```
System Info
```
release: 10
version: 10.0.19043
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
Python version 3.8.10
OpenCV version 4.5.3.56
```
##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``
@sergregory

**Comment by asmorkalov** [comment]
May be related: https://github.com/opencv/opencv-python/issues/518
