### ISSUE TITLE
I need opencv-python-headless wheel with gstreamer set ON

### ISSUE THREAD

**Issue by stu-github** [opencv/opencv-python#524]
### Expected behaviour

I want to study gstreamer in python,

So I need opencv-python-headless wheel with gstreamer set ON

Who can send me one?

**Comment by asmorkalov** [comment]
OpenCV team does not plan to release wheels with GStreamer support, but you can build it from source code by yourself. See OpenCV tutorial for details: https://docs.opencv.org/master/da/df6/tutorial_py_table_of_contents_setup.html

**Comment by yateya** [comment]
@stu-github build it yourself, use this snippet in ubuntu 20 image.

```
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev -y
sudo apt-get install build-essential cmake pkg-config -y
sudo apt-get install libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer1.0-dev -y
sudo python3 -m pip install ninja
python3 -m pip install numpy

git clone https://github.com/opencv/opencv-python
cd opencv-python/
git checkout 56 #opencv 4.5.3
export CMAKE_ARGS="-DOPENCV_ENABLE_NONFREE=ON"
export ENABLE_CONTRIB=1
export ENABLE_HEADLESS=1

pip3 wheel . --verbose
```
