### ISSUE TITLE
Problem installing with Pipenv

### ISSUE THREAD

**Issue by alistair-gemmell** [opencv/opencv-python#531]
### Expected behaviour

Should be able to install opencv-python (or opencv-contrib-python) into a pipenv

### Actual behaviour

When I get to install opencv-python, I get an error. opencv-python actually installs fine, and can be imported, but creating a Pipfile.lock now fails, and whenever I install further packages I get the same error warning messages. (If I previously has a Pipfile.lock, it is deleted by this installation attempt.) Pip, pipenv and python are all up-to-date. If I uninstall opencv-python, then everything starts working again.

### Steps to reproduce

- Working on Ubuntu 20.04 LTS
```
$ python --version
Python 3.8.10
$ pip --version
pip 21.2.4 from /home/SI/username/.local/lib/python3.8/site-packages/pip (python 3.8)
$ pipenv --version
pipenv, version 11.9.0
$ pipenv install opencv-python
Installing opencv-python…
Looking in indexes: https://pypi.python.org/simple
Collecting opencv-python
  Using cached opencv_python-4.5.3.56-cp38-cp38-manylinux2014_x86_64.whl (49.9 MB)
Requirement already satisfied: numpy>=1.17.3 in /home/SI/username/.local/share/virtualenvs/AI_RPC_Server-xYYUp_ir/lib/python3.8/site-packages (from opencv-python) (1.21.2)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.5.3.56

Adding opencv-python to Pipfile's [packages]…
Pipfile.lock (e0f10d) out of date, updating to (96dce2)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
elf.repository.get_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 174, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 222, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)
  File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 644, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 435, in run_egg_info
    call_subprocess(
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/utils/__init__.py", line 705, in call_subprocess
    raise InstallationError(
pip9.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpft9ek_lhbuild/opencv-python/
```

**Comment by directrix1** [comment]
I have this exact issue.

**Comment by directrix1** [comment]
After upgrading to newest pipenv, it appears to work for me.

**Comment by alistair-gemmell** [comment]
```
$ pip install pipenv
Requirement already satisfied: pipenv in /usr/lib/python3/dist-packages (11.9.0)
```

This may be a stupid question, but aren't I already on the newest version?

**Comment by skvark** [comment]
> 
> 
> ```
> $ pip install pipenv
> Requirement already satisfied: pipenv in /usr/lib/python3/dist-packages (11.9.0)
> ```
> 
> This may be a stupid question, but aren't I already on the newest version?

No, you're not. 11.9.0 was released on March 21, 2018. https://pypi.org/project/pipenv

**Comment by alistair-gemmell** [comment]
Thank you - turns out I had installed using `sudo apt install pipenv` which is hilariously out-of-date. I uninstalled that, then installed a newer version using `pipenv install --user pipenv` and updating my $PATH. (Replying to complete the history of my fix for posterity!)

**Comment by RomanSteinberg** [comment]
@alistair-gemmell I have the same problem and a bit more. 

According to [this](https://i.imgur.com/ZWgdGzv.png), [here](https://pypi.org/project/pipenv/2021.5.29/) is the latest version for today. [Pip says](https://i.imgur.com/DSop6e9.png) I have it. But I still have the [same problem](https://i.imgur.com/WsQn5vU.png). What should I do?

Also I'd like to mention that command
> `pipenv install --user pipenv`  

you suggested is incorrect. Probably, you mean `pip3 install --user pipenv`.  But [it says](https://i.imgur.com/XO5hUlh.png) everything is ok for me.
