### ISSUE TITLE
VideoWriter saved video does not support the Chinese filename

### ISSUE THREAD

**Issue by MrWindWz** [opencv/opencv-python#535]
opencv-python 3.4.10.37

cv2.VideoWriter("c:\我.mp4", fourcc, record_fps, (int(width), int(height)))

The saved file name is garbled

**Comment by asmorkalov** [comment]
What is your target platform? Please try the latest OpenCV release 4.5.3 and report if the issue is still there.

**Comment by MrWindWz** [comment]
> What is your target platform? Please try the latest OpenCV release 4.5.3 and report if the issue is still there.

window 10. Thanks, let me try it with 4.5.3.

**Comment by MrWindWz** [comment]
> What is your target platform? Please try the latest OpenCV release 4.5.3 and report if the issue is still there.
The problem remains,  win10, opencv-python==4.5.3.56

**Comment by asmorkalov** [comment]
Related issues in core library:

**Comment by asmorkalov** [comment]
Please track it issue in core repository. I close the ticket as it's not Python specific.
