### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by devendrasoni18** [opencv/opencv-python#536]
I have installed `opencv-python 4.1.2.30` version on `Python 3.6`. It is installed on `Windows server 2012 64bit`. 

When I import cv2 module it is throwing error as
`Traceback (most recent call last): File "<stdin>", line 1, in <module> File ".\env\lib\site-packages\cv2\__init__.py", line 3, in <module> from .cv2 import * ImportError: DLL load failed: The specified module could not be found.
`
I have already installed  Visual C++ redistributable 2015 on my Windows server 2012. 

Please suggest what else I can do?

**Comment by skvark** [comment]
Check out the README: https://github.com/opencv/opencv-python#frequently-asked-questions

**Comment by asmorkalov** [comment]
@devendrasoni18 any update?
