### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtC

### ISSUE THREAD

**Issue by liu-linxs** [opencv/opencv-python#541]
### Expected behaviour
In my study, I need OpencV to read some pictures, but these pictures (captcha) can't read properly

### Actual behaviour

When I run it, no matter whether there is a Chinese path or not, cv2 is always None, but libraries like PIL can read the image data I need.

### Steps to reproduce

img = cv2.imdecode(np.fromfile(img_name1, dtype=np.uint8), cv2.IMREAD_COLOR)
print(img)

- win10 x64
- opencv-python-4.5.3.56

![test1](https://user-images.githubusercontent.com/58330101/132843974-9befa884-8dfb-4f22-b054-b495ceaef6cb.jpg)

No matter how I run it, how I modify it, the result is always worse than expected, I don't know why.

**Comment by asmorkalov** [comment]
`cv::imread` does everything for you. You do not need to call `np.fromfile` and decoder separately.
