### ISSUE TITLE
Can I use Qt5 instead of Qt4 dependencies on Raspberry Pi?

### ISSUE THREAD

**Issue by pauljurczak** [opencv/opencv-python#542]
I'm running Ubuntu 21.04 for Raspberry Pi `ubuntu-21.04-preinstalled-desktop-arm64+raspi`, unfortunately `apt` can't find Qt4 libraries (`libqtgui4` and `libqt4-test`). I tried a few repositories recommended by others with no luck. Can I use `libqt5gui5` instead? I need only `imshow` to work.

**Comment by pauljurczak** [comment]
I tested the installation without Qt4 and `imshow` seems to work as expected. I'm getting this warning, though:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/paul/.local/lib/python3.9/site-packages/cv2/qt/plugins"
```
BTW, `libqt5gui5` is installed.

**Comment by skvark** [comment]
These packages ship with their own copy of Qt 5. Your system Qt is not used.

**Comment by pauljurczak** [comment]
Thank you. I was under the false impression that libqtgui4 and libqt4-test are required dependencies. Read it somewhere. I was also installing: libhdf5-dev libhdf5-serial-dev and libatlas-base-dev. Was that unnecessary?

What is this message about, then?
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/paul/.local/lib/python3.9/site-packages/cv2/qt/plugins"
```

**Comment by skvark** [comment]
The pre-built wheels ship currently only with X Window System (X11) plugin (qxcb). Your system is probably running Wayland instead of that. However, if imshow works, then your system supports also X11 and you can ignore that message.

https://doc.qt.io/qt-5/qpa.html#qpa-plugins

**Comment by skvark** [comment]
And yes, installing external dependencies is unnecessary when using the `manylinux` `opencv-python` wheels installed via `pip`. The packages depend of course on some external libraries such as Glibc and X11 libraries. but those are very likely already included in all desktop GNU/Linux distributions.

**Comment by pauljurczak** [comment]
Thank you for a quick response.
