### ISSUE TITLE
Android arm build has large file size after upgrading to macOS Big Sur

### ISSUE THREAD

**Issue by imagenier** [opencv/opencv-python#546]
Hi,

I made an Android build earlier this year when I was on an older version of macOS (Darwin 18.5.0 x86_64) and the file size of the _libopencv_java4.so_ was hovering around 10-20 MB depending on which modules I had enabled. Recently I upgraded my macOS to Big Sur (Darwin 20.5.0 x86_64) and performed the exact same build and now it is between 100MB-150MB depending on the modules I need for my purposes. I used CMake v3.20.0 and the same versions of OpenCV (the latest and older versions) in both instances. Is anybody else getting these large file sizes after upgrading? This is a 10x increase in file size and not really suitable for my needs. 

Thanks.

**Comment by asmorkalov** [comment]
Thanks for the issue report. The opencv-python repository is designed for OpenCV-Python package distributed with Pypi, not for Android or JAVA related questions. Please use github.com/opencv/opencv to report such issues.
For your case please check CMake configuration output for the following items (they usually have large footprint for binaries size:
- Debug build / debug symbols. `file` utility also says if binary contains debug symbols.
- Not used modules from OpenCV Contrib.
