### ISSUE TITLE
macOS Big Sur - .read() always returns (False, None)

### ISSUE THREAD

**Issue by nguye409** [opencv/opencv-python#548]
### Expected behaviour

An array to be returned to describe the image.

### Actual behaviour

Stuck in while loop for if frame is not None (which it always is)

### Steps to reproduce

- example code

```
import cv2

vc = cv2.VideoCapture(0)
rval, frame = vc.read()

while True:

  if frame is not None:
    cv2.imshow("preview", frame)

  rval, frame = vc.read()
  print(rval, frame)

  if cv2.waitKey(1) & 0xFF == ord('q'):
    break

vc.release()
cv2.imshow("output", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

```

- operating system

Mac OS Big Sur 
Version 11.6

- architecture (e.g. x86)

x86 2.3 GHz Quad-Core Intel Core i7

- opencv-python version

opencv-python-headless (Version 4.5.3.56)
Also tried:
opencv-python
opencv-contrib-python

Using python 3.8

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Could you provide more information about your setup: type of camera and how it's connected and cv.getBuildInformation() output. Does the camera work with other programs?

**Comment by abhiTronix** [comment]
@nguye409 Your code is wrong. Put `rval, frame = vc.read()` inside `while True` loop to fix it.
