### ISSUE TITLE
ImportError: libIlmImf-2_5.so.25: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by neuron-whisperer** [opencv/opencv-python#551]
### Expected behaviour

Installed OpenCV on Raspberry Pi 4 using fully updated Buster. Expected OpenCV to import successfully.

### Actual behaviour

"ImportError: libIlmImf-2_5.so.25: cannot open shared object file: No such file or directory"

### Steps to reproduce

(1) Obtain Raspberry Pi 4

(2) Install Buster

(3) Fully update Buster via sudo apt-get upgrade

(4) Install Python 3 via pyenv

(5) python -m pip install opencv-python (or opencv-python-headless)

(6) Start Python and import cv2

##### Issue submission checklist

 - [X] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [X] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [X] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [X] I'm using the latest version of ``opencv-python``

**Comment by LaurentBerger** [comment]
Can it be ["The library is now called libOpenEXR (instead of libIlmImf). "](https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.0.1)

**Comment by asmorkalov** [comment]
```
gcc: numpy/core/src/multiarray/hashdescr.c
gcc: build/src.linux-armv7l-3.10/numpy/core/src/multiarray/scalartypes.c
In file included from numpy/core/include/numpy/npy_math.h:596,
from numpy/core/src/multiarray/scalartypes.c.src:12:
numpy/core/src/npymath/npy_math_internal.h.src: In function ‘npy_modfl’:
numpy/core/src/npymath/npy_math_internal.h.src:490:21: warning: passing argument 2 of ‘modfl’ from incompatible pointer type [-Wincompatible-pointer-types]
return modf@c@(x, iptr);
^~~~
In file included from /home/hesperosaurus/.pyenv/versions/3.10.0/include/python3.10/pyport.h:210,
from /home/hesperosaurus/.pyenv/versions/3.10.0/include/python3.10/Python.h:63,
from numpy/core/src/multiarray/scalartypes.c.src:3:
/usr/include/arm-linux-gnueabihf/bits/mathcalls.h:110:1: note: expected ‘long double *’ but argument is of type ‘npy_longdouble *’ {aka ‘double *’}
__MATHCALL (modf,, (Mdouble __x, Mdouble *__iptr)) __nonnull ((2));
^
numpy/core/src/multiarray/scalartypes.c.src: In function ‘float_arrtype_hash’:
numpy/core/src/multiarray/scalartypes.c.src:2967:27: error: incompatible type for argument 1 of ‘_Py_HashDouble’
return _Py_HashDouble((double) PyArrayScalar_VAL(obj, @name@));
In file included from /home/hesperosaurus/.pyenv/versions/3.10.0/include/python3.10/Python.h:90,
from numpy/core/src/multiarray/scalartypes.c.src:3:
/home/hesperosaurus/.pyenv/versions/3.10.0/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
^~~~~~~~~~
numpy/core/src/multiarray/scalartypes.c.src:2967:12: error: too few arguments to function ‘_Py_HashDouble’
return _Py_HashDouble((double) PyArrayScalar_VAL(obj, @name@));
^~~~~~~~~~~~~~
```
Numpy build fails according to the log. It looks like you have multiple numpy versions on your system or some other build environment issues. It's out of OpenCV scope.

**Comment by dog-rose** [comment]
i have the same problem . 
openCV and numpy are both successfully installed but I still get the same error : 
********************************************************************************************
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raspberrypi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libIlmImf-2_5.so.25: cannot open shared object file: No such file or directory
******************************************************************************************************
I performed a clean installation for numpy , but the error persists .

**Comment by zhyx1996** [comment]
apt install libopenexr-dev
