### ISSUE TITLE
cap.isOpened() function return false in playing video from file

### ISSUE THREAD

**Issue by lwinmoe51** [opencv/opencv-python#557]
Hello guy 
Help me!
I install openCV by using pip (python) from command prompt 

pip install opencv-python

cap.isOpened() function return ''false''. 

I googled and found the solutions related with ffmpeg.  I downloaded and installed ffmpeg.  But still not working. 

I tried both  ''.avi'' and ''.mp4''. 

How can i solve this problem?

**Comment by asmorkalov** [comment]
please provide information about your platform and cv.getBuildInformation() output for your OpenCV instance.

**Comment by asmorkalov** [comment]
`cv.getBuildInformation()` function output: https://docs.opencv.org/master/db/de0/group__core__utils.html#ga0ae377100bc03ce22322926bba7fdbb5

**Comment by alalek** [comment]
Also run videoio code under debug mode: https://docs.opencv.org/master/de/db1/group__videoio__registry.html

**Comment by asmorkalov** [comment]
You need to add cv.getBuildInInformation() call right after import cv2 and before actual OpenCV usage, print its output to console and publish the log here. OpenCV does not decode video by itself, but uses 3rd party libraries (like FFmpeg or GStreamer) and system APIs (like media Foundation, DirectShow). The back-ends are configured in compile time and stored in the library. The function output helps to understand where you are to make the next step.

**Comment by LIBBYbrand21** [comment]
בפלט הפונקציה cv.getBuildInformation() אני באמת רואה ש אין לי FFMPEG:
![צילום מסך 2023-10-22 115230](https://github.com/opencv/opencv-python/assets/117980350/1fc93319-4e9a-4a88-97ba-142e594cd3bd)
איך אני מתקנת את זה?
