### ISSUE TITLE
Minimum requirement of  Numpy  of 1.21.0 for Mac M1 cannot be satisfied

### ISSUE THREAD

**Issue by curiolearner** [opencv/opencv-python#573]
For Mac M1 using Apple TensorFlow, the requirement of Numpy is 1.19.* 
Numpy 1.21.1 is not compatible.
So  the following requirement must be met, then there is no way of using it. 
if sys.platform == "darwin" and sys.version_info[:2] >= (3, 6) and platform.machine() == "arm64":
        minimum_supported_numpy = "1.21.0"

Unfortunately, this is a dependency of some. Is there a productive way of circumventing this?

**Comment by asenyaev** [comment]
Hi @curiolearner!

I don't see any wheels of `numpy` with version 1.19.* for macOS with M1 (arm64). They only start from `1.21.0`. 

I also tried to build `numpy==1.19.*` from source, usually it fails on python 3.7, 3.8, 3.9.

In addition, `numpy==1.18.5` is in a [script](https://github.com/apple/tensorflow_macos/blob/master/scripts/install_venv.sh#L51) in tensorflow_macos repository, but again, I don't see the certain wheel on PyPi ([files for 1.18.5 version](https://pypi.org/project/numpy/1.18.5/#files)).

**Comment by tlightsky** [comment]
the Apple [Official](https://developer.apple.com/metal/tensorflow-plugin/) `tensorflow-macos` seems depends on `1.19.*`
which is different from `1.21.*`

**Comment by asenyaev** [comment]
Hi @tlightsky!
I've tried to find any supported wheel of `numpy` for macos arm64, but there are no wheel. Moreover, I couldn't build `numpy==1.19.*` from source on Mac mini with Apple Silicon.
