### ISSUE TITLE
Opencv-Python has no code hint in pycharm

### ISSUE THREAD

**Issue by Monster-DP** [opencv/opencv-python#574]
### Expected behaviour
Opencv -python module can automatically prompt code in pycharm, such as numpy.
![image](https://user-images.githubusercontent.com/47738288/139057224-a78f9932-e59c-4d00-8c4a-1221a1ef1eeb.png)

### Actual behaviour
Opencv Python is successfully installed in pycham, but there is no code prompt for cv2 in pycham. It just can't prompt the code, but the program runs normally. I have tried many methods on the Internet, but they can't succeed.
![image](https://user-images.githubusercontent.com/47738288/139056894-6e1c8290-e6e2-41e5-bfcc-ddf8e6e87df2.png)
![image](https://user-images.githubusercontent.com/47738288/139056961-aaaa685d-c503-4c4a-a1bb-4ec3f9881a5f.png)
![image](https://user-images.githubusercontent.com/47738288/139058128-39d4034f-c277-4405-84b9-4fc2ad9c18bf.png)

### Steps to reproduce

- operating system  win11 22000.282
- architecture  x86
- opencv-python version  4.5.4.58

**Comment by dianchia** [comment]
Same here. Have to downgrade to 4.5.3.56 for it to work.

**Comment by andogy** [comment]
I found a way to do this!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```python
from cv2 import cv2
```

because cv2's init is in cv2.cv2

plz close the issue

**Comment by andogy** [comment]
now you can just use
```python
import cv2
```

**Comment by bvitaz-ck** [comment]
```
import cv2
```

Does not provide code hint in version 4.5.5.62. 

```
from cv2 import cv2
```

Causes PyCharm to claim `'cv2' is not declared in __all__`

**Comment by GuidoBartoli** [comment]
I had the same problem, but [this](https://github.com/opencv/opencv/issues/20997#issuecomment-1328068006) worked fine for me!

**Comment by alexisgaziello** [comment]
This worked for me: https://stackoverflow.com/a/73087052/7731571
