### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'getBuildInformation'

### ISSUE THREAD

**Issue by mathieuseguin** [opencv/opencv-python#586]
### Expected behaviour

After building opencv-python, I would expect to have access to the build information.

### Actual behaviour

```
➜  opencv-python git:(master) ✗ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.getBuildInformation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2' has no attribute 'getBuildInformation'
```

The import path looks correct:
```
>>> cv2.__file__
'/usr/local/src/opencv-python/cv2/__init__.py'
```

### Steps to reproduce

Here is a full log of the [building process](https://gist.github.com/mathieuseguin/12beacedaaeba8b5116677420d546164). 

I'm using a regular ubuntu:latest docker image, with GStreamer installed.

I get the same result, regardless if I follow the steps from the README, or the ones outlined by @ES-Alexander (https://discuss.bluerobotics.com/t/opencv-python-with-gstreamer-backend/8842)

##### Issue submission checklist

 - [X] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
 - [X] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
 - [X] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [X] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Since OpenCV 4.5.4 OpenCV-Python package consists of *.so file (as usual) and Python code (cv.Mat. G-API bindings, init). Looks like your package is loaded incorrectly (*.so part is missing). I have not found suspicious warnings in your logs. I'll take a look into the issue in meantime.

**Comment by alalek** [comment]
Please add logs from cv2 importer. Use this flag to enable debug mode: https://github.com/opencv/opencv/blob/4.5.4/modules/python/test/tests_common.py#L13

**Comment by mathieuseguin** [comment]
@alalek it doesn't seem to give us much more information unfortunately: 
```
$ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.OpenCV_LOADER_DEBUG = True
>>> import cv2
>>> cv2.getBuildInformation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2' has no attribute 'getBuildInformation'
```

**Comment by mathieuseguin** [comment]
What's built in the _skbuild directory works though:
```
$ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/docker/venv/lib/python3.8/site-packages']
>>> sys.path.insert(0, '/home/docker/opencv-python/_skbuild/linux-x86_64-3.8/cmake-install/cv2')
>>> sys.path
['/home/docker/opencv-python/_skbuild/linux-x86_64-3.8/cmake-install/cv2', '', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/docker/venv/lib/python3.8/site-packages']
>>> import cv2
>>> cv2.getBuildInformation()
'\nGeneral configuration for OpenCV 4.5.4 =====================================\n
```

**Comment by alalek** [comment]
Dump `cv2.__file__` to see that is actually loaded.

**Comment by asmorkalov** [comment]
@mathieuseguin friendly reminder.

**Comment by mathieuseguin** [comment]
@asmorkalov I was able to get passed it by compiling via pip instead, then went on vacation.
I appreciate the help!
Thanks

**Comment by ianblitz** [comment]
@mathieuseguin What exactly did you do to fix this? I'm running into the same issue after building with GStreamer.

**Comment by mathieuseguin** [comment]
Sorry for the late reply @ianblitz!

My package was actually installed correctly. The issue was that I was running `python` from the `opencv-python` directly itself, which contains a cv2 directory with an empty `__init__.py` file inside.

By default python will import from the current directory. If you look at your sys.path:
```
>>> sys.path
['', '/Users/mathieu/.pyenv/versions/3.9.1/lib/python39.zip', '/Users/mathieu/.pyenv/versions/3.9.1/lib/python3.9', '/Users/mathieu/.pyenv/versions/3.9.1/lib/python3.9/lib-dynload', '/Users/mathieu/.pyenv/versions/3.9.1/lib/python3.9/site-packages']
```

When importing a module python will look inside `''` (current directory) before looking inside ` '/Users/mathieu/.pyenv/versions/3.9.1/lib/python3.9/site-packages'` (where the wheel is actually installed).

Because the opencv-python source has a `cv2` directory that includes an `__init__.py` file, python considers it to be a valid module and loads it. Consequently it does not continue to loop through the other paths until the `site-packages`.

**Comment by Authoriztiondimension** [comment]
![image](https://user-images.githubusercontent.com/76044901/179147666-b38a401c-cff2-4c32-806c-0fd4aff58b16.png)
does your cv2 module look like this?

**Comment by ES-Alexander** [comment]
@Authoriztiondimension the contents of that file will depend on which version you have installed.

I've got 
`~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/cv2/version.py`:
```python
opencv_version = "4.5.5+209d32e"
contrib = False
headless = False
ci_build = False
```

`~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/cv2/__init__.py`:
```python
'''
OpenCV Python binary extension loader
'''
import os
import importlib
import sys

from .cv2 import *
from .cv2 import _registerMatType
from . import mat_wrapper
from . import gapi
from . import misc
from . import utils
from . import data
from . import version

__all__ = []

try:
    import numpy
    import numpy.core.multiarray
except ImportError:
    print('OpenCV bindings requires "numpy" package.')
    print('Install it via command:')
    print('    pip install numpy')
    raise

# TODO
# is_x64 = sys.maxsize > 2**32


def __load_extra_py_code_for_module(base, name, enable_debug_print=False):
    module_name = "{}.{}".format(__name__, name)
    export_module_name = "{}.{}".format(base, name)
    ...
```
which is at least quite similar to yours.
