### ISSUE TITLE
Getting empty string

### ISSUE THREAD

**Issue by Robert969696** [opencv/opencv-python#594]
Doing it like:
```
img = qrcode.make("coś dla fslkjdfiushfiuaehrfiuewqrhfiuqwehABCD123534566745456 aaasd-(//\\&**&^*&^^*(@#Bs1")
img.save("pic.jpg")
d = cv2.QRCodeDetector()
val, points, straight_qrcode =  d.detectAndDecode(cv2.imread("pic.jpg"))
print(val)
```

This gives me empty string back. Why is that?
P.S When i remove last char (1) from my string  it reads it properly..

**Comment by tezz-io** [comment]
This is not an issue with cv2 or qrcode libraries. By default qrcode.make assumes the box size of the QR Code as 10x10. A 10x10 QR code is not big enough to hold your 87 characters of python string data. Its limit is around 86 utf-8 characters. Therefore you are getting this error. Try increasing boxsize to 11 or higher in qrcode.make function call

**Comment by tp1050** [comment]
> Doing it like:
> 
> ```
> img = qrcode.make("coś dla fslkjdfiushfiuaehrfiuewqrhfiuqwehABCD123534566745456 aaasd-(//\\&**&^*&^^*(@#Bs1")
> img.save("pic.jpg")
> d = cv2.QRCodeDetector()
> val, points, straight_qrcode =  d.detectAndDecode(cv2.imread("pic.jpg"))
> print(val)
> ```
> 
> This gives me empty string back. Why is that? P.S When i remove last char (1) from my string it reads it properly..


what do you mean by removing the last char? 
you mean from resul tset returned ?or the thing you have turned into qr?
