### ISSUE TITLE
waitKey detect GPIO from Raspbery

### ISSUE THREAD

**Issue by vwasteels** [opencv/opencv-python#599]
### Expected behaviour

Detect GPIO instead of Keyboard pressed

### Actual behaviour

Working fine with keyboard

### Steps to reproduce

I try to control a video from a Raspberry GPIO Button, the script works fine with keyboard inputs, but I'd like to know a way to plug the GPIO in,

Thanks !!

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ x The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
OpenCV cv::wayKey function triggers internal UI libraries event loop and has 2 purposes:
