### ISSUE TITLE
ImportError since Update 4.5.5.62 on Google Colab

### ISSUE THREAD

**Issue by lukasdrescher1** [opencv/opencv-python#601]
### Expected behaviour

Everything worked fine until the release of version 4.5.5.62 a few hours ago. Since then I get the following Import Error:

### Actual behaviour

```
/usr/local/lib/python3.7/dist-packages/cv2/__init__.py in <module>()
      7 
      8 from .cv2 import *
----> 9 from .cv2 import _registerMatType
     10 from . import mat_wrapper
     11 from . import gapi

ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)
```

I'm using cv2 with the module albumentations (https://albumentations.ai/) on Google Colab. I tried to uninstall opencv-python and install version 4.5.4.60 but the error remains. I changed nothing in my code, which run well until the release of the new version.

### Steps to reproduce

(on Google Colab)

`import cv2`
or
```
!pip uninstall opencv-python
!pip install opencv-python==4.5.4.60
import cv2
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by alalek** [comment]
> /usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so

Looks like wrong binary file is used (it doesn't belong to the new package).
Correct path should look like: `.../site-packages/cv2/cv2.abi3.so`. `cv2.abi3.so` is important change of the new package version.

Use `sys.OpenCV_LOADER = True` to gather debug information.

**Comment by lukasdrescher1** [comment]
Thank you!
Installing albumentations without binaries worked:
`!pip install -U albumentations --no-binary qudida,albumentations`
