### ISSUE TITLE
cv2.connectedComponentsWithStats raises weird error on latest version

### ISSUE THREAD

**Issue by SHA65536** [opencv/opencv-python#602]
### Actual behaviour

When using cv2.connectedComponentsWithStats I am presented with a _mysterious_ error
```
nLabels, labels, stats, centroids = cv2.connectedComponentsWithStats(text_score_comb.astype(np.uint8), connectivity=4)
cv2.error: Unknown C++ exception from OpenCV code
```
Took me a long time to figure out what's wrong because of the vague error message... 
Finally solved it by switching back to version 4.5.4.60

### Steps to reproduce

Windows 10 64bit
opencv-python 4.5.5.62
Use the cv2.connectedComponentsWithStats function with the latest opencv-python version

**Comment by alalek** [comment]
Lets track it here: https://github.com/opencv/opencv/issues/21366

**Comment by noxqs** [comment]
For me removing the parameter connectivity=4 from cv2.connectedComponentsWithStats fixed it. This is in cojunction with easyOCR.

**Comment by robertschweizer** [comment]
FYI: This still fails with the latest release `opencv-python` 4.5.5.64, because it does not include a newer OpenCV C++ library than 4.5.5.62. 

The OpenCV C++ library has been fixed, but not released yet.

**Comment by rinnegann** [comment]
> For me removing the parameter connectivity=4 from cv2.connectedComponentsWithStats fixed it. This is in cojunction with easyOCR.

Thanks!,This has worked for me.

**Comment by GeraldLJW** [comment]
> For me removing the parameter connectivity=4 from cv2.connectedComponentsWithStats fixed it. This is in cojunction with easyOCR.

thanks！！！！

**Comment by SuperHero19999** [comment]
> For me removing the parameter connectivity=4 from cv2.connectedComponentsWithStats fixed it. This is in cojunction with easyOCR.

Where can I found this function to remove the parameter and is it working with easyOCR ?

**Comment by bhumika-cashify** [comment]
> 

thankyou so much.

**Comment by bhumika-cashify** [comment]
> For me removing the parameter connectivity=4 from cv2.connectedComponentsWithStats fixed it. This is in cojunction with easyOCR.

thankyou so much.

**Comment by Nadinegp** [comment]
> For me removing the parameter connectivity=4 from cv2.connectedComponentsWithStats fixed it. This is in cojunction with easyOCR.

Where can I find the file? what is it called?

**Comment by mikeboharsik** [comment]
For anyone else experiencing this issue, @robertschweizer seemed to have it right. I ran the following command:

`pip install --upgrade opencv-contrib-python`

and the exception went away. The suggestion from @noxqs works as well but obviously is far less ideal than having the packages "fix" themselves.
