### ISSUE TITLE
VideoWriter bitrate

### ISSUE THREAD

**Issue by banders** [opencv/opencv-python#603]
A comment in [issue 521](https://github.com/opencv/opencv-python/issues/521) indicates that it's possible to control the bitrate of the VideoWriter.  Can anyone point to an example of how the bitrate could be set via the VideoWriter constructor or other function?

**Comment by abhiTronix** [comment]
OpenCV provides flags like [`VIDEOWRITER_PROP_QUALITY `, `VIDEOWRITER_PROP_FRAMEBYTES`, `VIDEOWRITER_PROP_NSTRIPES`](https://docs.opencv.org/3.4/d4/d15/group__videoio__flags__base.html#ga41c5cfa7859ae542b71b1d33bbd4d2b4) to change and view some VideoWriter properties.
