### ISSUE TITLE
Segmentation Fault Using cv2.connectedComponentsWithStats

### ISSUE THREAD

**Issue by chrisdonlan** [opencv/opencv-python#606]
### Expected behaviour

Returns valid outputs corresponding to the following line of code given a `numpy.ndarray` binary image (black = 0, white = 255) of uint8 pixels: 

```
self.count, self.mask, stats, centroids = cv2.connectedComponentsWithStats(
    cc_img.astype(np.uint8)), connectivity=connectivity
)
```

### Actual behaviour

After raising my minimum allowed `opencv-python` version from 4.5.1 to 4.5.4, this error emerged.

### Steps to reproduce

- example code

```
import numpy as np

X = np.random.randint(0, 1, (100, 100))
X_img = (X * 255).astype(np.uint8)

import cv2
count, mask, stats, centroids = cv2.connectedComponentsWithStats(X_img, connectivity=4)
```

Result: `Segmentation fault: 11`

- operating system

MacOSX "Darwin", `Kernel Version 20.6.0`

- architecture (e.g. x86)

x86_64

- opencv-python version

opencv-python                     4.5.5.62

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by chrisdonlan** [comment]
I am not sure this is the right repo to submit this issue, let me know and I will re-submit on the `opencv` project.  

Unfortunately, in order to submit in the main `opencv` project, I have to refactor this reproducible example into C++ code (likely on this work laptop to trigger the bug).  With that in mind, I am submitting here first -- apologies if it is the wrong project.

**Comment by alalek** [comment]
Already submitted everywhere. Duplicate.

**Comment by k-for-code** [comment]
faced this same issue
