### ISSUE TITLE
`Sobel` does not work for large size image?

### ISSUE THREAD

**Issue by shiba24** [opencv/opencv-python#609]
Hi team, thank you for your everyday development. I've found a bug probably.

### Actual behaviour

`Sobel` does not work for large size image.

### Steps to reproduce

- opencv-python==4.5.3.56
- python 3.9.9
- Operating System / Platform => MacBook Pro (M1, 2020)

```
import cv2
import numpy as np

print(cv2.__version__)

f = np.zeros((1, 200, 300), dtype=np.float64)
sob = cv2.Sobel(f, cv2.CV_64F, 1, 0, ksize=3)
print("OK:", sob.shape)

f = np.zeros((1, 400, 600), dtype=np.float64)
sob = cv2.Sobel(f, cv2.CV_64F, 1, 0, ksize=3)  # This is error
```

The error is

```
-  python3 cv_test.py
4.5.3
OK: (1, 200, 300)
Traceback (most recent call last):
  File "cv_test.py", line 12, in <module>
    sob = cv2.Sobel(f, cv2.CV_64F, 1, 0, ksize=3)
cv2.error: OpenCV(4.5.3) /private/var/folders/b7/g6qfbypj0tq32j5_trjh516r0000gn/T/pip-req-build-_pm4jjil/opencv/modules/core/src/matrix.cpp:1102: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'locateROI'
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)

 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

Should I submit this issue to the original OpenCV repository?

**Comment by asmorkalov** [comment]
OpenCV expects numpy array with shape (h, w, c). You have to swap order to use numpy array as image.
