### ISSUE TITLE
Problem displaying grayscale image overlaid on a blank canvas

### ISSUE THREAD

**Issue by chinge55** [opencv/opencv-python#611]
### Expected behaviour
Overlaying a Grayscale image on a white canvas and displaying it with cv2.imshow() should display a grayscale image overlaid on a blank canvas.
### Actual behaviour
A binary image is displayed by cv2.imshow() instead of a grayscale image. All the information between 0 and 255 are lost. This is an issue with imshow because cv2.imwrite() works as expected.
### Steps to reproduce

- example code
```python
    img1 = np.random.randint(0, 255, (500, 500)).astype("uint8")  # Random image
    img2 = np.ones((1500, 1500)) * 255  # Blank Canvas
    img2[: img1.shape[0], : img1.shape[1]] = img1
    cv2.imshow("Output", img2)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    plt.imshow(img2, cmap="gray")
    plt.title("expected output")
    plt.show()
```

- Operating System: Ubuntu 20.04
- architecture: x64
- opencv-python version: 4.5.5

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by alalek** [comment]
```
print(cv.utils.dumpInputArray(img2))
```

**Comment by chinge55** [comment]
> ```
> print(cv.utils.dumpInputArray(img2))
> ```

The results for img1 and img2 are :
```
InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=2250000 dims(-1)=2 size(-1)=1500x1500 type(-1)=CV_64FC1
InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=250000 dims(-1)=2 size(-1)=500x500 type(-1)=CV_32SC1
```

**Comment by alalek** [comment]
> CV_32SC1

Should be 8U (uint8 numpy array).
