### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'TrackerMOSSE_create'

### ISSUE THREAD

**Issue by violet2422** [opencv/opencv-python#616]
My cv2 version  is 
![image](https://user-images.githubusercontent.com/73391269/150320689-fff203d4-7c83-4d2a-9b76-97bc6be01297.png)
Why can't I run the tracker?

**Comment by MauryaRitesh** [comment]
The latest version of  OpenCV now has the "TrackerMOSSE_create" under the [legacy class](https://docs.opencv.org/4.5.1/d0/d20/classcv_1_1legacy_1_1TrackerMOSSE.html), instead of

```tracker = cv2.TrackerMOSSE_create()```

use

```tracker = cv2.legacy.TrackerMOSSE_create()```

**Comment by asmorkalov** [comment]
The tracker is implemented in Contrib repository and was moved to legacy namespace at 2020-10-28. MauryaRitesh is right and you need to use new namespace to create object.

**Comment by SHariVigneshwaran** [comment]
tracker = cv2.legacy.TrackerMOSSE_create() 
This command is not still working for me.
<img width="985" alt="Screenshot 2022-12-20 at 18 58 36" src="https://user-images.githubusercontent.com/92072842/208678263-91774b27-18da-4715-92fd-2ab13a6ee916.png">

**Comment by skvark** [comment]
Seems to be working fine:

 ``pip install opencv-contrib-python``                     
 ```bash 
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.legacy.TrackerMOSSE_create()
<cv2.legacy.TrackerMOSSE 0000022C41AEBCD0>
```

Make sure you have installed the correct package that contains the extra modules in addition to the main modules: `opencv-contrib-python`.

1. Before you install `opencv-contrib-python`, remove `opencv-python` with `pip uninstall opencv-python`. 
2. See the README for more detailed installation instructions.

In the future, check out the comprehensive OpenCV documentation for more info on which APIs are included in the different packages: https://docs.opencv.org/4.6.0/index.html

**Comment by SHariVigneshwaran** [comment]
Still its showing the same error :(

**Comment by skvark** [comment]
Make sure that you have the correct package installed:

```python
import cv2
print(cv2.getBuildInformation())
```

**Comment by Mumer5490** [comment]
Good sir thanks you share your knowledge

**Comment by TuanTuanC** [comment]
> 

Thanks!This method successfully helps me solve the problem.

**Comment by liang050404** [comment]
还是用不了

**Comment by MuslimEngineer** [comment]
> 还是用不了

scipy  ==1.10.1
opencv-contrib-python   ==  4.9.0.80
