### ISSUE TITLE
opencv-python depends on vulnerable libpng15

### ISSUE THREAD

**Issue by brammerc** [opencv/opencv-python#622]
### Expected behaviour

Based on issue #506, expected opencv-python==4.5.5.62 to depend on libpng16.

### Actual behaviour

package dependencies for opencv-python==4.5.5.62 include libpng15, which is highly vulnerable. 

### Steps to reproduce

- ubuntu:20.04, python 3.8
- x86
- opencv-python==4.5.5.62

##### Issue submission checklist

 - [x ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Duplicate https://github.com/opencv/opencv-python/issues/614
