### ISSUE TITLE
Please update the ffmpeg and gnutls versions used by libopencv

### ISSUE THREAD

**Issue by cameron-a-johnson** [opencv/opencv-python#625]
### Feature Request

For the latest pip-installed version of opencv-python (4.5.5.62), libopencv is using very dated versions of ffmpeg and gnutls, which are known to have vulnerabilities. Would it be possible to release a version with those dependencies updated?

Please let me know if I'm posting this request to the correct repo. 

##### Issue submission checklist

 - [✅  ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [✅  ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ✅ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [✅  ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Related issues: https://github.com/opencv/opencv-python/issues/622, https://github.com/opencv/opencv-python/issues/614

**Comment by asmorkalov** [comment]
OpenCV-Python team works on security-fix release of the package.

**Comment by asmorkalov** [comment]
Done with releases 4.5.5.64 and 3.4.17.63.
