### ISSUE TITLE
No matching distribution found for opencv-contrib-python==4.2.0.32

### ISSUE THREAD

**Issue by EralpBay** [opencv/opencv-python#631]
> pip3 install opencv-contrib-python==4.2.0.32
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.2.0.32 (from versions: 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62)
ERROR: No matching distribution found for opencv-contrib-python==4.2.0.32
> python3 --version
Python 3.9.9

Hello, I'd like to ask why did this version go missing? is this expected?

**Comment by MikePendo** [comment]
I am a little bit new to openCV and python development I have the same issue, but I have installed pyenv and set it to 3.8 according to the docs it should be supported but I still have the same error:
```
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-python==4.2.0.32
WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
You should consider upgrading via the '/Users/m/.pyenv/versions/pypy3.8-7.3.11/bin/python -m pip install --upgrade pip' command.
```

**Comment by dids-reyes** [comment]
> I am a little bit new to openCV and python development I have the same issue, but I have installed pyenv and set it to 3.8 according to the docs it should be supported but I still have the same error:

Same i tried `3.8`, `3.7` and `3.6` and im still getting that error

did you find a solution?

**Comment by Koa28062004** [comment]
> There it is: https://pypi.org/project/opencv-contrib-python/4.2.0.32/#files
> 
> You are using Python 3.9. There are no wheels for that release for Python 3.9 because Python 3.9 did not exist back then.

But I use mac with ARM chip, in your given website, it does not have for this ARM Mac. What should I do ?

**Comment by sergregory** [comment]
> But I use mac with ARM chip, in your given website, it does not have for this ARM Mac. What should I do ?

@Koa28062004 there were no builds for Apple Silicon at that moment. First M1s were released in November 2020, while you're refering to the release of OpenCV from February 2020 :-)
I'd suggest to take a newer OpenCV version, most probably it'll work without any changes in your code.
