### ISSUE TITLE
opencv headless missing librairy on Rpi zero w

### ISSUE THREAD

**Issue by lucapatanella** [opencv/opencv-python#633]
### Expected behaviour

When I import `cv2` it should initialize

### Actual behaviour

When I import `cv2` I have `Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory`

I tried to install the `libopenjp2.so.7` librairy via `sudo apt-get install libopenjp2-7-dev` but in the end I have other librairies that are missing. I only need the core librairies of Opencv and with the limited cpu power of the Rpi zero I don't want to overload it with unused librairies that I don't use. So I don' tknow if it might be an issue of the opencv headless install or an issue of the Rpi. A thing to know is I that before trying with the headless version I got Opencv via `sudo apt install python3-opencv` but decided to remove it because of the CPU usage when loading the full module.  Might be an issue in that side also. 

### Steps to reproduce

- Run  ` python3 -c 'import cv2; print(cv2.__version__)'`
- I am running the latest Debian Buster version available for the Rpi zero w
-  opencv is `opencv-python-headless` version  `4.5.5.62`
- I have python  `version 3.7.3`

##### Issue submission checklist

 - [X] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [X] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [X] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [X] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Hello @lucapatanella. Thanks for the issue report.
- python3-opencv package is built by Debian/Pi maintainers and is not maintained by OpenCV team.
- Pypi provides different binaries for different ARM systems (or even build from source code, if suitable binary is not available). So I need more information about your setup to help: Pi version or m.b. `cat /proc/cpuinfo` output. Also I need to know, if you run 64-bit or 32-bit version of OS and python.

**Comment by asmorkalov** [comment]
@lucapatanella do you have any updates on the issue?

**Comment by asmorkalov** [comment]
@lucapatanella Friendly reminder.
