### ISSUE TITLE
How to install with OpenGL support on Ubuntu

### ISSUE THREAD

**Issue by EyescannerJE** [opencv/opencv-python#634]
Hi!
I can't find any up to date instructions of how to install opencv-python with OpenGL support.
I want everything that is included in the regular install `pip install opencv-python` and also OpenGL.

**Environment**
OS: Ubuntu 20.04
Python: 3.8.10
Pip: 22.0.4

**What I tried**  
`CMAKE_ARGS="-DWITH_OPENGL=ON" pip install --no-binary=opencv-contrib-python opencv-contrib-python`  
That command did not install OpenGL and I also lost GTK

**Comment by asmorkalov** [comment]
The command you use forces pip to build OpenCV package from sources rather use ready binary. OpenCV detects available 3rdparties like FFmpeg, GTK, libjpeg, libpng on CMake stage and disables them, if some of them are not available. So, you need to install `-dev` packages for all 3rdparties that you want to be there. `cv.getBuildInformation()` call in python returns cmake configuration status and you can check if all required 3rd parties are found and enabled during the build. For GTK support you need to install `libgtk2.0-dev` and some other GTK-OpenGL integration packages.

**Comment by EyescannerJE** [comment]
I see,
How do I find out which packages I need?

**Comment by EyescannerJE** [comment]
The result from `cv.getBuildInformation()` with the regular pip install:
```
GUI:                           QT5
    QT:                          YES (ver 5.15.0 )
      QT OpenGL support:         NO

```
If I only want to change `QT OpenGL support:` to `YES` can that be done easily?

**Comment by EyescannerJE** [comment]
> The command you use forces pip to build OpenCV package from sources rather use ready binary. OpenCV detects available 3rdparties like FFmpeg, GTK, libjpeg, libpng on CMake stage and disables them, if some of them are not available. So, you need to install `-dev` packages for all 3rdparties that you want to be there. `cv.getBuildInformation()` call in python returns cmake configuration status and you can check if all required 3rd parties are found and enabled during the build. For GTK support you need to install `libgtk2.0-dev` and some other GTK-OpenGL integration packages.

Is there no easy way to get OpenGL support in any form?

**Comment by asmorkalov** [comment]
The only way is to rebuild OpenCV with all required dependencies and flags.
