### ISSUE TITLE
cp37 for windows is missing

### ISSUE THREAD

**Issue by quaesitor-scientiam** [opencv/opencv-python#653]
### Expected behaviour

Write here how did you expect the library to function.
PyPi download link

### Actual behaviour
PyPi missing cp37 for windows.  The cp36 is available.

Write here what went wrong.
Don't know.

### Steps to reproduce
Visit  https://pypi.org/project/opencv-python/4.5.5.64/#files
- example code  n/a
- operating system  Windows
- architecture (e.g. x86)  x64
- opencv-python version  4.5.5.64

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by quaesitor-scientiam** [comment]
I was able to build a cp37  wheel using scikit-build 0.13.0 do you all want that to add to your repository?

**Comment by asmorkalov** [comment]
Couple of releases ago OpenCV team switched to LIMITED_API builds for Python binaries. It means that the dll uses minimal stable Python API and is compatible with all supported python versions. So you can use the same package for Python 3.6+, no need to install specific version for 3.7.
