### ISSUE TITLE
"pip uninstall opencv-python" not unstalling package

### ISSUE THREAD

**Issue by d-kleine** [opencv/opencv-python#654]
### Expected behaviour

`pip uninstall opencv-python` unstalling package

### Actual behaviour

`pip uninstall opencv-python` getting stuck in infinite loop, not unstalling package

### Steps to reproduce

- `pip uninstall opencv-python`
- MS Windows 10
- x64
- 4.5.5 `(4.5.5.64)`

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
The issue may be related to OS or pip. OpenCV does not implement uninstall steps. It's done by pip by default.

**Comment by d-kleine** [comment]
Okay, then I'm closing this issue here 💹
