### ISSUE TITLE
ImportError: cannot import name '_registerMatType' from 'cv2.cv2'

### ISSUE THREAD

**Issue by KaleIsPale** [opencv/opencv-python#655]
### Expected behaviour

Using opencv and some other modules to make a simple screen recorder (OBS is a bit heavy and causes a lot of lag while recording, so I thought building a light-weight python screen recorder might help). I expected my module to work, ask me a filename and then open the video showing me what I am recording. 

### Actual behaviour

It gives me an ImportError about some function or something:
```    
from .cv2 import _registerMatType
ImportError: cannot import name '_registerMatType' from 'cv2.cv2
```

### Steps to reproduce

-Sample Code:  `import cv2`
-Operating System: Windows 10
-Architecture: x64
-opencv-python version: 4.5.5.64

##### Issue submission checklist

 - [Yes] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [Yes] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [Yes] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [Yes] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Could you provide `cv.getBuildInformation` output and small reproducer for the issue?

**Comment by KaleIsPale** [comment]
> Could you provide details on your setup: python version? How is it installed?

Sry for the late response. 
Python version: 3.8.6
I installed python from the official website (i.e. the windows installer)

**Comment by asmorkalov** [comment]
And how is OpenCV Installed? Self-built? Pip? Conda?

**Comment by KaleIsPale** [comment]
Pip

**Comment by asenyaev** [comment]
Hi @KaleIsPale!

I have tried to reproduce this issue on different Windows devices with different Python versions and have not found this issue.

My steps to reproduce:
1. Install `opencv-python` with 4.5.5.64 version with `--no-cache` `--force-reinstall` flags:
```
python3 -m pip install --no-cache --force-reinstall opencv-python==4.5.5.64
```
2. Import OpenCV:
```
import cv2
```

I know where this line from, we append an `__init__.py` file with extra imports [here](https://github.com/opencv/opencv-python/blob/64/setup.py#L375). It needs to handle proper imports for. However, the next release will be without these extra imports in case of changes in python loader of OpenCV.

In addition, the issue on your side can be in case of an already installed `opencv-python` version (it can be even `opencv-python-headless` or `opencv-contrib-python`). Could you check it?
Example line:
`python3.8 -m pip list`

**Comment by KaleIsPale** [comment]
Ok so I uninstalled ALL the modules (i.e. opencv-python, opencv-python-headless and opencv-contrib-python) and installed cv2 again, and it seems to be working (Probably because the module was updated to v4.6)
Anyways, TSYM For the help!

**Comment by asenyaev** [comment]
@KaleIsPale, thank you for the feedback!
