### ISSUE TITLE
Type hint better

### ISSUE THREAD

**Issue by HouLingLXH** [opencv/opencv-python#656]
I expect type of parameters and returned value will be specific, 

Now I modified the file in python_stubs to realized it, but it is a not good way.

How to do it better ?

### Expected behaviour

![image](https://user-images.githubusercontent.com/30954632/163900889-0a94b667-ae35-4390-b5f5-c3ae7500a318.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/30954632/163900756-26d90d7e-47d8-4d5f-a818-51d3862a96dc.png)

**Comment by asmorkalov** [comment]
OpenCV team is working on Python stubs with static types, but it's not there yet. I cannot give you any ETA for the feature, please follow release notes.

**Comment by VadimLevin** [comment]
@asmorkalov we can close this issue since mentioned PR is merged

**Comment by asmorkalov** [comment]
Sure
