### ISSUE TITLE
ModuleNotFoundError: No module named 'skbuild' with 4.6.0.66 and not 4.5.5.64

### ISSUE THREAD

**Issue by Christian-B** [opencv/opencv-python#674]
We use github action to test our code

We install in the very latest off all tools including pip
 python -m pip install --upgrade setuptools wheel
 python -m pip install pip

This worked (and still) fine with opencv-python  4.5.5.64

it failes
  File "/tmp/easy_install-otpfl9qw/opencv-python-4.6.0.66/setup.py", line 10, in <module>
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
ModuleNotFoundError: No module named 'skbuild'

Only changing our requirements to 
opencv-python < 4.6.0.66

and the exact same workflow works.

Our github action
"runs-on: ubuntu-20.04"

**Comment by rahulporuri** [comment]
We're seeing the same issue as above ^.

**Comment by Christian-B** [comment]
Respect!
Uncapped and now works on both github actions and Jenkins (which had also failed)

ok to close on my part

**Comment by rahulporuri** [comment]
same here, our CI is happy now. Thanks @asenyaev , this can be closed.

**Comment by asenyaev** [comment]
Thanks for the feedback! Closing this issue.
