### ISSUE TITLE
No x86_64.manylinux2014 wheel binary on v4.6.0.66 

### ISSUE THREAD

**Issue by bordax** [opencv/opencv-python#675]
### Expected behaviour

I expect a binary installation using `pip install opencv-python`.

### Actual behaviour

When installing in Linux x86_64 plataforms, we have to built from source. This slowdown automatic CI, like Github Actions.

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by peterdudfield** [comment]
I think im seeing the same error when building a Docker file from python:3.9-silm-buster

https://github.com/openclimatefix/nowcasting_api/runs/6793058401?check_suite_focus=true

**Comment by bordax** [comment]
The binary package is on air now: https://pypi.org/project/opencv-python/4.6.0.66/#files

So, I'm closing this issue.
